services:
  skav-build:
    build:
      context: .
    image: skav:${IMAGE_TAG:-latest}

  skav-run:
    image: skav:${IMAGE_TAG:-latest}
    volumes:
      - .:/app/skav
    command: tail -f /dev/null
