#!/usr/bin/env python3
"""
Token Usage Models

This module defines Pydantic models for token usage metadata in Claude Code
transcripts. Usage information tracks the number of tokens consumed during
API interactions.

The models include:
    - Usage: Main usage container with input/output tokens, caching info
    - CacheCreation: Statistics about cache creation (ephemeral caches)
    - ServerToolUse: Usage for server-side tools (web fetch, web search)

Token counts include:
    - input_tokens: Tokens sent to the model
    - output_tokens: Tokens generated by the model
    - cache_read_input_tokens: Tokens read from cache
    - cache_creation_input_tokens: Tokens used for cache creation
"""

from typing import Any, Literal

from pydantic import BaseModel


class CacheCreation(BaseModel):
    ephemeral_1h_input_tokens: int
    ephemeral_5m_input_tokens: int


class ServerToolUse(BaseModel):
    web_fetch_requests: int | None = None
    web_search_requests: int | None = None


class Usage(BaseModel):
    input_tokens: int
    output_tokens: int

    cache_creation: CacheCreation | None = None
    cache_creation_input_tokens: int | None = None
    cache_read_input_tokens: int | None = None
    inference_geo: str | None = None

    # TODO: check the data type of `iterations` item
    iterations: list[Any] | None = None

    server_tool_use: ServerToolUse | None = None

    # TODO: check the enumerable values of `service_tier` and `speed`
    service_tier: Literal["standard"] | str | None = None
    speed: Literal["standard"] | str | None = None
